import type { TreeSourceNode } from "@finos/vuu-ui-controls";

export const folderData: TreeSourceNode[] = [
  // prettier-ignore
  {
    id: "2018",
    label: "2018",
    icon: "folder",
    childNodes: [
      {
        id: "Q1",
        label: "Q1",
        childNodes: [
          {
            id: "January",
            label: "January",
            childNodes: [
              { id: "child-1", label: "Child 1", icon: "folder" },
              { id: "child-2", label: "Child 2", icon: "folder" },
              { id: "child-3", label: "Child 3", icon: "folder" },
              { id: "child-4",
                label: "Child 4",
                icon: "folder",
              },
              { id: "child-5",
                label: "Child 5",
                icon: "folder",
              },
              { id: "child-6",
                label: "Child 6",
                icon: "folder",
              },
              { id: "child-7",
                label: "Child 7",
                icon: "folder",
              },
              {
                id: "child-8",
                label: "Child 8",
                icon: "folder",
              },
              {
                id: "child-9",
                label: "Child 9",
                icon: "folder",
              },
              {
                id: "child-10",
                label: "Child 10",
                icon: "folder",
              },
              {
                id: "child-11",
                label: "Child 11",
                icon: "folder",
              },
              {
                id: "child-12",
                label: "Child 12",
                icon: "folder",
              },
              {
                id: "child-13",
                label: "Child 13",
                icon: "folder",
              },
              {
                id: "child-14",
                label: "Child 14",
                icon: "folder",
              },
              {
                id: "child-15",
                label: "Child 15",
                icon: "folder",
              },
              {
                id: "child-16",
                label: "Child 16",
                icon: "folder",
              },
              {
                id: "child-17",
                label: "Child 17",
                icon: "folder",
              },
              {
                id: "child-18",
                label: "Child 18",
                icon: "folder",
              },
              {
                id: "child-19",
                label: "Child 19",
                icon: "folder",
              },
              {
                id: "child-20",
                label: "Child 20",
                icon: "folder",
              },
              {
                id: "child-21",
                label: "Child 21",
                icon: "folder",
              },
              {
                id: "child-22",
                label: "Child 22",
                icon: "folder",
              },
              { id: "child-23", label: "Child 23", icon: "folder" },
              { id: "child-24", label: "Child 24", icon: "folder" },
              { id: "child-25", label: "Child 25", icon: "folder" },
              { id: "child-26", label: "Child 26", icon: "folder" },
              { id: "child-27", label: "Child 27", icon: "folder" },
              { id: "child-28", label: "Child 28", icon: "folder" },
              { id: "child-29", label: "Child 29", icon: "folder" },
              { id: "child-30", label: "Child 30", icon: "folder" },
              { id: "child-31", label: "Child 31", icon: "folder" },
              { id: "child-32", label: "Child 32", icon: "folder" },
              { id: "child-33", label: "Child 33", icon: "folder" },
              { id: "child-34", label: "Child 34", icon: "folder" },
              { id: "child-35", label: "Child 35", icon: "folder" },
              { id: "child-36", label: "Child 36", icon: "folder" },
              { id: "child-37", label: "Child 37", icon: "folder" },
              { id: "child-38", label: "Child 38", icon: "folder" },
              { id: "child-39", label: "Child 39", icon: "folder" },
              { id: "child-40", label: "Child 40", icon: "folder" },
              { id: "child-41", label: "Child 41", icon: "folder" },
              { id: "child-42", label: "Child 42", icon: "folder" },
              { id: "child-43", label: "Child 43", icon: "folder" },
              { id: "child-44", label: "Child 44", icon: "folder" },
              { id: "child-45", label: "Child 45", icon: "folder" },
              { id: "child-46", label: "Child 46", icon: "folder" },
              { id: "child-47", label: "Child 47", icon: "folder" },
              { id: "child-48", label: "Child 48", icon: "folder" },
              { id: "child-49", label: "Child 49", icon: "folder" },
              { id: "child-50", label: "Child 50", icon: "folder" },
              { id: "child-51", label: "Child 51", icon: "folder" },
              { id: "child-52", label: "Child 52", icon: "folder" },
              { id: "child-53", label: "Child 53", icon: "folder" },
              { id: "child-54", label: "Child 54", icon: "folder" },
              { id: "child-55", label: "Child 55", icon: "folder" },
              { id: "child-56", label: "Child 56", icon: "folder" },
              { id: "child-57", label: "Child 57", icon: "folder" },
              { id: "child-58", label: "Child 58", icon: "folder" },
              { id: "child-59", label: "Child 59", icon: "folder" },
              { id: "child-60", label: "Child 60", icon: "folder" },
              { id: "child-61", label: "Child 61", icon: "folder" },
              { id: "child-62", label: "Child 62", icon: "folder" },
              { id: "child-63", label: "Child 63", icon: "folder" },
              { id: "child-64", label: "Child 64", icon: "folder" },
              { id: "child-65", label: "Child 65", icon: "folder" },
              { id: "child-66", label: "Child 66", icon: "folder" },
              { id: "child-67", label: "Child 67", icon: "folder" },
              { id: "child-68", label: "Child 68", icon: "folder" },
              { id: "child-69", label: "Child 69", icon: "folder" },
              { id: "child-70", label: "Child 70", icon: "folder" },
            ],
            icon: "folder",
          },
        ],
        icon: "folder",
      },
      {
        id: "Q2",
        label: "Q2",
        childNodes: [
          {
            id: "Q2-1",
            label: "Q2-1",
            childNodes: [
              { id: "Q2-1-1",
               label: "Q2-1-1",
                childNodes: [
                  {
                    id : "Q2-1-1-1",
                    label: "Q2-1-1-1",
                    icon: "folder",
                  },
                ],
                icon: "folder",
              },
            ],
            icon: "folder",
          },
          {
            id: "Q2-2",
            label: "Q2-2",
            childNodes: [
              {
                id: "Q2-2-1",
                label: "Q2-2-1",
                childNodes: [
                  {
                    id: "Q2-2-1-1",
                    label: "Q2-2-1-1",
                    icon: "folder",
                  },
                ],
                icon: "folder",
              },
            ],
            icon: "folder",
          },
        ],
        icon: "folder",
      },
      {
        id: "Q3",
        label: "Q3",
        icon: "folder",
      },
      {
        id: "Q4",
        label: "Q4",
        icon: "folder",
      },
    ],
  },
  {
    id: "2019",
    label: "2019",
    childNodes: [
      {
        id: "Q1",
        label: "Q1",
        icon: "folder",
      },
    ],
    icon: "folder",
  },
];
