vuu.webroot="vuu-ui/deployed_apps/app-vuu-example"
vuu.certPath="example/main-clickhouse/src/main/resources/certs/cert.pem"
vuu.keyPath="example/main-clickhouse/src/main/resources/certs/key.pem"
vuu.ssl=true
