name: Setup Vuu UI
description: "Installs NodeJS and project dependencies"

runs:
  using: "composite"
  steps:
    - name: Install NodeJS
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
      with:
        node-version: "22"

    - name: Cache dependencies
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-

    - name: Install dependencies
      shell: bash
      run: cd ./vuu-ui && npm install
