name: Setup Vuu UI
description: "Installs NodeJS and project dependencies"

runs:
  using: "composite"
  steps:
    - name: Install NodeJS
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
      with:
        node-version: "24.x"

    - name: Cache dependencies
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-

    - name: Checkout UserAdmin package source
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      with:
        repository: heswell/vuu-websocket
        ref: 60792d0a40a9c0b01d738a98247dc9c04987ff9a
        path: .vuu-websocket

    - name: Install dependencies
      shell: bash
      run: |
        cd ./vuu-ui
        npm run link:user-admin -- ../.vuu-websocket
        npm install
