import { SettingsSchema } from "@vuu-ui/vuu-shell";

export const scrollableSettingsFormSchema: SettingsSchema = {
  properties: [
    {
      name: "field1",
      label: "Mode",
      values: ["light", "dark"],
      defaultValue: "light",
      type: "string",
    },
    {
      name: "field2",
      label: "Date Formatting",
      values: ["dd/mm/yyyy", "mm/dd/yyyy", "dd MMMM yyyy"],
      defaultValue: "dd/mm/yyyy",
      type: "string",
    },
    {
      name: "field3",
      label: "Region",
      values: [
        { value: "us", label: "US" },
        { value: "apac", label: "Asia Pacific" },
        { value: "emea", label: "Europe, Middle East & Africa" },
      ],
      defaultValue: "apac",
      type: "string",
    },
    {
      name: "field4",
      label: "Greyscale",
      defaultValue: false,
      type: "boolean",
    },
    {
      name: "field5",
      label: "User Name",
      type: "string",
    },
    {
      name: "field6",
      label: "Mode",
      values: ["light", "dark"],
      defaultValue: "light",
      type: "string",
    },
    {
      name: "field7",
      label: "Date Formatting",
      values: ["dd/mm/yyyy", "mm/dd/yyyy", "dd MMMM yyyy"],
      defaultValue: "dd/mm/yyyy",
      type: "string",
    },
    {
      name: "field8",
      label: "Region",
      values: [
        { value: "us", label: "US" },
        { value: "apac", label: "Asia Pacific" },
        { value: "emea", label: "Europe, Middle East & Africa" },
      ],
      defaultValue: "apac",
      type: "string",
    },
    {
      name: "field9",
      label: "Greyscale",
      defaultValue: false,
      type: "boolean",
    },
    {
      name: "field10",
      label: "User Name",
      type: "string",
    },
    {
      name: "field11",
      label: "Mode",
      values: ["light", "dark"],
      defaultValue: "light",
      type: "string",
    },
    {
      name: "field12",
      label: "Date Formatting",
      values: ["dd/mm/yyyy", "mm/dd/yyyy", "dd MMMM yyyy"],
      defaultValue: "dd/mm/yyyy",
      type: "string",
    },
    {
      name: "field13",
      label: "Region",
      values: [
        { value: "us", label: "US" },
        { value: "apac", label: "Asia Pacific" },
        { value: "emea", label: "Europe, Middle East & Africa" },
      ],
      defaultValue: "apac",
      type: "string",
    },
    {
      name: "field14",
      label: "Greyscale",
      defaultValue: false,
      type: "boolean",
    },
    {
      name: "field15",
      label: "User Name",
      type: "string",
    },
    {
      name: "field16",
      label: "Mode",
      values: ["light", "dark"],
      defaultValue: "light",
      type: "string",
    },
    {
      name: "field17",
      label: "Date Formatting",
      values: ["dd/mm/yyyy", "mm/dd/yyyy", "dd MMMM yyyy"],
      defaultValue: "dd/mm/yyyy",
      type: "string",
    },
    {
      name: "field18",
      label: "Region",
      values: [
        { value: "us", label: "US" },
        { value: "apac", label: "Asia Pacific" },
        { value: "emea", label: "Europe, Middle East & Africa" },
      ],
      defaultValue: "apac",
      type: "string",
    },
    {
      name: "field19",
      label: "Greyscale",
      defaultValue: false,
      type: "boolean",
    },
    {
      name: "field20",
      label: "User Name",
      type: "string",
    },
    {
      name: "field21",
      label: "Mode",
      values: ["light", "dark"],
      defaultValue: "light",
      type: "string",
    },
    {
      name: "field22",
      label: "Date Formatting",
      values: ["dd/mm/yyyy", "mm/dd/yyyy", "dd MMMM yyyy"],
      defaultValue: "dd/mm/yyyy",
      type: "string",
    },
    {
      name: "field23",
      label: "Region",
      values: [
        { value: "us", label: "US" },
        { value: "apac", label: "Asia Pacific" },
        { value: "emea", label: "Europe, Middle East & Africa" },
      ],
      defaultValue: "apac",
      type: "string",
    },
    {
      name: "field24",
      label: "Greyscale",
      defaultValue: false,
      type: "boolean",
    },
    {
      name: "field25",
      label: "User Name",
      type: "string",
    },
    {
      name: "field26",
      label: "Mode",
      values: ["light", "dark"],
      defaultValue: "light",
      type: "string",
    },
    {
      name: "field27",
      label: "Date Formatting",
      values: ["dd/mm/yyyy", "mm/dd/yyyy", "dd MMMM yyyy"],
      defaultValue: "dd/mm/yyyy",
      type: "string",
    },
    {
      name: "field28",
      label: "Region",
      values: [
        { value: "us", label: "US" },
        { value: "apac", label: "Asia Pacific" },
        { value: "emea", label: "Europe, Middle East & Africa" },
      ],
      defaultValue: "apac",
      type: "string",
    },
    {
      name: "field29",
      label: "Greyscale",
      defaultValue: false,
      type: "boolean",
    },
    {
      name: "field30",
      label: "User Name",
      type: "string",
    },
    {
      name: "field31",
      label: "Mode",
      values: ["light", "dark"],
      defaultValue: "light",
      type: "string",
    },
    {
      name: "field32",
      label: "Date Formatting",
      values: ["dd/mm/yyyy", "mm/dd/yyyy", "dd MMMM yyyy"],
      defaultValue: "dd/mm/yyyy",
      type: "string",
    },
    {
      name: "field33",
      label: "Region",
      values: [
        { value: "us", label: "US" },
        { value: "apac", label: "Asia Pacific" },
        { value: "emea", label: "Europe, Middle East & Africa" },
      ],
      defaultValue: "apac",
      type: "string",
    },
    {
      name: "field34",
      label: "Greyscale",
      defaultValue: false,
      type: "boolean",
    },
    {
      name: "field35",
      label: "User Name",
      type: "string",
    },
    {
      name: "field36",
      label: "Mode",
      values: ["light", "dark"],
      defaultValue: "light",
      type: "string",
    },
    {
      name: "field37",
      label: "Date Formatting",
      values: ["dd/mm/yyyy", "mm/dd/yyyy", "dd MMMM yyyy"],
      defaultValue: "dd/mm/yyyy",
      type: "string",
    },
    {
      name: "field38",
      label: "Region",
      values: [
        { value: "us", label: "US" },
        { value: "apac", label: "Asia Pacific" },
        { value: "emea", label: "Europe, Middle East & Africa" },
      ],
      defaultValue: "apac",
      type: "string",
    },
    {
      name: "field39",
      label: "Greyscale",
      defaultValue: false,
      type: "boolean",
    },
    {
      name: "field40",
      label: "User Name",
      type: "string",
    },
    {
      name: "field41",
      label: "Mode",
      values: ["light", "dark"],
      defaultValue: "light",
      type: "string",
    },
    {
      name: "field42",
      label: "Date Formatting",
      values: ["dd/mm/yyyy", "mm/dd/yyyy", "dd MMMM yyyy"],
      defaultValue: "dd/mm/yyyy",
      type: "string",
    },
    {
      name: "field43",
      label: "Region",
      values: [
        { value: "us", label: "US" },
        { value: "apac", label: "Asia Pacific" },
        { value: "emea", label: "Europe, Middle East & Africa" },
      ],
      defaultValue: "apac",
      type: "string",
    },
    {
      name: "field44",
      label: "Greyscale",
      defaultValue: false,
      type: "boolean",
    },
    {
      name: "field45",
      label: "User Name",
      type: "string",
    },
  ],
};
